---
title: "Instrumental Phonetics 2021"
---

Final Mark =0.6 $\times$ (HW) + 0.4 $\times$ (Exam)

### 1. Introduction to Acoustic Phonetics

* (20.01.2021)	[Lec 1](https://github.com/agricolamz/2021_HSE_m_Instrumental_phonetics/raw/master/docs/lec%201/21.01.16_Acoustic_Phonetics_lec_1.pdf) ([video](https://youtu.be/AD2KYpXlo4A))
    * [additional materials on waves](https://pudding.cool/2018/02/waveforms/) 
* (27.01.2021) [Lec2](https://github.com/agricolamz/2021_HSE_m_Instrumental_phonetics/raw/master/docs/2021.01.27_bioacoustics.pdf) ([video](https://youtu.be/NoZxQiu1fzs))
    * [database of bird calls](https://www.xeno-canto.org/) (and it is not the only one)
    * [marine mammal sound database](https://cis.whoi.edu/science/B/whalesounds/index.cfm)
    * [invisibilia podcast episode on sounds](https://www.npr.orgo/2020/03/25/821648089/the-last-sound)
* (27.01.2021)	Lab 1: [Praat](http://www.fon.hum.uva.nl/praat/). Symbols for [consonats](http://www.fon.hum.uva.nl/praat/manual/Phonetic_symbols__consonants_1.png), [vowels](http://www.fon.hum.uva.nl/praat/manual/Phonetic_symbols__vowels_1.png) and [diacritics](http://www.fon.hum.uva.nl/praat/manual/Phonetic_symbols__diacritics.html)
* HW 1 (due to 10.02.2021): 
    * Create the  annotation for [this sound file](https://github.com/agricolamz/2018_m_Instrumental_Phonetics/blob/master/docs/materials/andi_plosives.wav?raw=true) containing words *bek':ub* (hot), *wuk:udu* (fall down), *tʃ'ek'a* (foot) and *t'uka* (goat). Here is [an example](https://raw.githubusercontent.com/agricolamz/2018_m_Instrumental_Phonetics/master/docs/hw1.png).
    * Send the `.TextGrid` file to the course assistant [Nastya Safonova](mailto:nastya-saff@yandex.ru) with the topic `Instrumental Phonetics: HW 1`
* (03.02.2021) [Lec3](https://github.com/agricolamz/2021_HSE_m_Instrumental_phonetics/raw/master/docs/18.02.10_Vowels.pdf) ([video](https://youtu.be/zdTIzDHnwQo))
* (03.02.2021) Lab
    * [sound](https://goo.gl/IzpUyo)
    * [TextGrid](https://goo.gl/4tGthZ) (press Ctrl+S in order to save it to your PC)
    * [`phonfieldwork`](https://docs.ropensci.org/phonfieldwork/)

* (10.02.2021) [Lec4](https://github.com/agricolamz/2021_HSE_m_Instrumental_phonetics/raw/master/docs/lec%203/2020.03.06_Sonorants.pdf) ([video](https://youtu.be/Ff7c8SUOxws))
* (10.02.2021) [Lab4](https://github.com/agricolamz/2021_HSE_m_Instrumental_phonetics/raw/master/docs/18.02.17_Sonorants_sem_3.pdf)
    * [Andi nasals](https://goo.gl/5D9DNR)
    * [R script for visualising spectral slices](https://github.com/agricolamz/2021_HSE_m_Instrumental_phonetics/raw/master/scripts/visualise_spectral_slices.R)

* (17.02.2021) [Lec5](https://github.com/agricolamz/2021_HSE_m_Instrumental_phonetics/raw/master/docs/20.03.12_Obstruents_lec_4.pdf) ([video](https://youtu.be/89gC40Azv7g))
* (17.02.2021) [Lab5](https://github.com/agricolamz/2021_HSE_m_Instrumental_phonetics/raw/master/docs/18.02.24_Obstruents_sem_4.pdf)
    * [fricatives](https://goo.gl/hvdviI), [fricatives' TextGrid](https://goo.gl/pza6tx), Extracted data: [ɬ](https://goo.gl/wo3QZN), [s](https://goo.gl/eNZQKa), [sh](https://goo.gl/NgeVSX), [x](https://goo.gl/oDYvbJ), [χ](https://goo.gl/vZQfZG) 
    * [fricatives' R script](https://goo.gl/SdGlZr)
    * [plosives](https://goo.gl/PZA8WY), [plosives' TextGrid](https://goo.gl/1ZFtJt), Extracted data: [plosives' duration](https://goo.gl/NExChs)
    * [plosives' R script](https://gist.githubusercontent.com/agricolamz/c4c5e6dfd5cfcd8052e5f03db7b12f64/raw/54248887fef342aad90db42f5439456dda5f1d88/CD_VOT.R)

* (24.02.2021) [Lec6 on prosody](https://github.com/agricolamz/2021_HSE_m_Instrumental_phonetics/raw/master/docs/2021_prosody.pdf) ([video](https://youtu.be/jQwZ7KcmIzE))
* (24.02.2021) [Lec6 on reading spectrograms](https://github.com/agricolamz/2021_HSE_m_Instrumental_phonetics/raw/master/docs/2021_reading_spectrorgams.pdf)

* (10.03.2021) [Lec7 on methods of phonetic research](https://github.com/agricolamz/2021_HSE_m_Instrumental_phonetics/raw/master/docs/2021_methods.pdf) ([video](https://youtu.be/eUmfhdsOhws))
* (10.03.2021) [Lec7 on perception](https://github.com/agricolamz/2021_HSE_m_Instrumental_phonetics/raw/master/docs/2021_perception.pdf) ([video](https://youtu.be/eUmfhdsOhws))
    * [Audition and anatomy](https://www.youtube.com/watch?v=PeTriGTENoc)
    * [McGurk effect](https://www.youtube.com/watch?v=kzo45hWXRWU)
    * [Endoscopy (larynx)](https://youtu.be/-1Fv7IPmJo4?t=18)
    * [Palatography](https://youtu.be/8Sh5hFnIuS4)
    * [Electropalatography](https://youtu.be/1w90b2xY9f8)
    * [Ultrasound tongue imaging (UTI)](https://youtu.be/b9URTdEe_Ko)
    * [MRI](https://youtu.be/2t_UpKuSB8A)

* (17.03.2021) Lec8 ([video](https://youtu.be/n71fZxyiA2E))

* (25.03.2021) Lec9 [video](https://youtu.be/JsMrWUU7vo0)
    * [pdf with word spectrum](https://github.com/agricolamz/2021_HSE_m_Instrumental_phonetics/raw/master/docs/spectrum_reading_training.pdf)
    * [autograding google form with more tasks](https://docs.google.com/forms/d/e/1FAIpQLSfAfqyMxVx4S3iTZNEBMZHXhw1uiZb_ieyyA9bjK9TRGzCb8g/viewform)

* (14.04.2021) Lec10 ([video](https://youtu.be/Gg5GhqnL3OU))
    * [files for training](https://github.com/agricolamz/2021_HSE_m_Instrumental_phonetics/raw/master/docs/phonfieldwork_training.zip)
    * [R script](https://github.com/agricolamz/2021_HSE_m_Instrumental_phonetics/raw/master/docs/phonfieldwork_training.R)

* HW 2 (due to 28.04.2021):
    * make a recording of syllables [ka], [ki], [ko], [ku] pronounced by two different people
    * use `phonfiledwork` and `Praat` for merging and preannotation sounds
    * manually adjust annotation after `phonfieldwork`
    * create a plot that analyze vowel duration split by speaker and vowel (see the R script from the last lecture)
    * Send your sound, `.TextGrid` and obtained plot to the course assistant [Nastya Safonova](mailto:nastya-saff@yandex.ru) with the topic `Instrumental Phonetics: HW 2`


### Reference:

* Ashby, M., J. Maidment (2005). Introducing phonetic science. Cambridge University Press.
* Bickford, A. C., R. Floyd (2006). Articulatory Phonetics: Tools for Analyzing the World’s Languages SIL International. 
* Boersma,  P.,  D.  Weenink  (2013). Praat:    doing  phonetics  by  computer  (version 5.3.51)[computer program]. retrieved 2 june 2013.
* Fant, G. (1971). Acoustic theory of speech production:  with calculations based on X-ray studies of Russian articulations, Volume 2.  Walter de Gruyter.
* Fuchs, S., M. Toda„ M. Żygis (2010). Turbulent sounds:  an interdisciplinary guide, Volume 21.  Walter de Gruyter.
* Fulop, S. (2011). Speech spectrum analysis.  Springer Science & Business Media.
* Gick, B., I. Wilson D. Derrick (2012). Articulatory phonetics. John Wiley & Sons.
* Gordon, M., P. Ladefoged (2001).  Phonation types: a cross-linguistic overview. Journal of Phonetics 29 (4), 383–406.
* Harrington, J. (2010). Phonetic analysis of speech corpora. John Wiley & Sons.
* [Hon Hunt, E. (2009). Acoustic Characterization of the Glides /j/ and /w/ in American English](https://dspace.mit.edu/bitstream/handle/1721.1/52797/547382338-MIT.pdf;sequence=2)
* Johnson, K. (2011). Acoustic and auditory phonetics. John Wiley & Sons.
* Ladefoged, P., S. F. Disner (2012). Vowels and consonants. John Wiley & Sons.
Ladefoged, P., I. Maddieson. (1996). The Sounds of the World’s Languages Oxford, Cambridge: Blackwell Publishers.
* Rorabaugh, C. B. (2010). Notes on Digital Signal Processing: Practical Recipes for Design, Analysis and Implementation Prentice Hall